### ISSUE TITLE
I cannot connect to my own github api that fetches one file which is posts.json for some reason??

### ISSUE THREAD

**Issue by 4kunu** [neocities/neocities#531] opened 2024-08-10 18:27 UTC
whenever i try to make a post it displays 
![obraz](https://github.com/user-attachments/assets/59d2cf66-a6d8-4284-a67a-cb5af37581ce)
which is annoying since i want to make a forum page ^_^ 
maybe you could make the csp allow connect-src blob and self or better yet github apis in general

**Comment by therainydev** [comment] 2024-08-15 04:16
It's been disabled for new users; see #484.

**Comment by 4kunu** [comment] 2024-08-15 14:46
my account is 3 weeks old

**Comment by kyledrake** [comment] 2024-08-15 21:48
Indeed this is expected behavior and a WONTFIX, apologies if you expected this behavior but it's not a bug. The supporter plan allows for CSP.

We had way too much abuse and we had to do this to keep the site working well and showing up in search engines.

**Closed by kyledrake** 2024-08-15 21:48 UTC
