### ISSUE TITLE
Directory not found error while searching site files

### ISSUE THREAD

**Issue by Prouser123** [neocities/neocities#232] opened 2016-11-15 20:10 UTC
When searching the site files of my site on the Dashboard, when i click on a directory (eg on home > files > content and click on files) I am greeted with this error [http://imgur.com/a/2xccT](http://imgur.com/a/2xccT). This is very annoying and decreases my productivity. Please fix this.

This happens on every browser and computer I try.

Many thanks,
Prouser123

**Comment by kyledrake** [comment] 2017-03-03 19:18
I cannot reproduce this, so I'm hoping it's been resolved. Closing...

**Closed by kyledrake** 2017-03-03 19:18 UTC
